package main

import (
	"context"

	"google.golang.org/grpc/codes"
	"google.golang.org/grpc/status"
)

// grpcServer implements EmbedServiceServer (generated by protoc).
// It delegates to the same *server used by the HTTP handlers, sharing
// the embedder and its mutex so both transports serialise correctly.
type grpcServer struct {
	UnimplementedEmbedServiceServer
	srv *server
}

func (g *grpcServer) Health(_ context.Context, _ *HealthRequest) (*HealthResponse, error) {
	return &HealthResponse{Status: "ok"}, nil
}

func (g *grpcServer) Embed(_ context.Context, req *EmbedRequest) (*EmbedResponse, error) {
	if req.Text == "" {
		return nil, status.Error(codes.InvalidArgument, "text is required")
	}

	g.srv.mu.Lock()
	embedding, err := g.srv.embedder.GetEmbeddings(req.Text)
	g.srv.mu.Unlock()

	if err != nil {
		return nil, status.Errorf(codes.Internal, "%v", err)
	}

	return &EmbedResponse{
		Embedding:  embedding,
		Dimensions: int32(len(embedding)),
	}, nil
}

func (g *grpcServer) EmbedBatch(_ context.Context, req *EmbedBatchRequest) (*EmbedBatchResponse, error) {
	if len(req.Texts) == 0 {
		return nil, status.Error(codes.InvalidArgument, "texts are required")
	}

	g.srv.mu.Lock()
	embeddings, err := g.srv.embedder.GetEmbeddingsBatch(req.Texts)
	g.srv.mu.Unlock()

	if err != nil {
		return nil, status.Errorf(codes.Internal, "%v", err)
	}

	dim := int32(0)
	if len(embeddings) > 0 {
		dim = int32(len(embeddings[0]))
	}

	vectors := make([]*EmbeddingVector, len(embeddings))
	for i, emb := range embeddings {
		vectors[i] = &EmbeddingVector{Values: emb}
	}

	return &EmbedBatchResponse{
		Embeddings: vectors,
		Dimensions: dim,
	}, nil
}
